"""Add semantic tool cache

Revision ID: 3ce9928e4340
Revises: 8df8b13ee7fb
Create Date: 2026-08-23 17:55:37.437307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3ce9928e4340'
down_revision: Union[str, Sequence[str], None] = '8df8b13ee7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_tool_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('result_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_tool_cache_tool_name'), 'semantic_tool_cache', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_tool_cache_tool_name'), table_name='semantic_tool_cache')
    op.drop_table('semantic_tool_cache')
    # ### end Alembic commands ###
