"""add deeper fighter stats

Revision ID: 536f1af10de5
Revises: e91d03ee02d7
Create Date: 2026-08-23 19:03:03.378789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536f1af10de5'
down_revision: Union[str, Sequence[str], None] = 'e91d03ee02d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('reach_cm', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('slpm', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('str_acc', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('sapm', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('str_def', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('td_avg', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('td_acc', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('td_def', sa.Float(), nullable=True))
    op.add_column('fighters', sa.Column('sub_avg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'sub_avg')
    op.drop_column('fighters', 'td_def')
    op.drop_column('fighters', 'td_acc')
    op.drop_column('fighters', 'td_avg')
    op.drop_column('fighters', 'str_def')
    op.drop_column('fighters', 'sapm')
    op.drop_column('fighters', 'str_acc')
    op.drop_column('fighters', 'slpm')
    op.drop_column('fighters', 'reach_cm')
    op.drop_column('fighters', 'height_cm')
    # ### end Alembic commands ###
