"""Add better-auth issuer

Revision ID: 6ed4a9912488
Revises: 536f1af10de5
Create Date: 2026-08-24 02:05:40.087741

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ed4a9912488"
down_revision: str | Sequence[str] | None = "536f1af10de5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("idToken", sa.Text(), nullable=True))
    op.add_column("account", sa.Column("accessTokenExpiresAt", sa.DateTime(), nullable=True))
    op.add_column("account", sa.Column("refreshTokenExpiresAt", sa.DateTime(), nullable=True))
    op.add_column("account", sa.Column("scope", sa.Text(), nullable=True))
    op.add_column("account", sa.Column("issuer", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "issuer")
    op.drop_column("account", "scope")
    op.drop_column("account", "refreshTokenExpiresAt")
    op.drop_column("account", "accessTokenExpiresAt")
    op.drop_column("account", "idToken")
    # ### end Alembic commands ###
