"""Add better-auth tables

Revision ID: 79835368f13f
Revises: 96bf775cb325
Create Date: 2026-08-23 18:05:07.831487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79835368f13f'
down_revision: Union[str, Sequence[str], None] = '96bf775cb325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('emailVerified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('accountId', sa.String(length=255), nullable=False),
    sa.Column('providerId', sa.String(length=255), nullable=False),
    sa.Column('accessToken', sa.Text(), nullable=True),
    sa.Column('refreshToken', sa.Text(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('ipAddress', sa.Text(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('account')
    op.drop_table('verification')
    op.drop_table('user')
    # ### end Alembic commands ###
