"""Add Fight unique constraint

Revision ID: 8694c2d3702c
Revises: a961da61a0df
Create Date: 2026-08-27 17:30:50.983720

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8694c2d3702c'
down_revision: str | Sequence[str] | None = 'a961da61a0df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_fight_event_fighters', 'fights', ['event_id', 'fighter_a_id', 'fighter_b_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_fight_event_fighters', 'fights', type_='unique')
    # ### end Alembic commands ###
