"""Add admin plugin fields to User

Revision ID: 8df8b13ee7fb
Revises: 5d2c3af0a5cb
Create Date: 2026-08-23 18:21:41.558312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df8b13ee7fb'
down_revision: Union[str, Sequence[str], None] = '5d2c3af0a5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('banReason', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('banExpires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'banExpires')
    op.drop_column('user', 'banReason')
    op.drop_column('user', 'banned')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
