"""Add Fight and Ranking models

Revision ID: a961da61a0df
Revises: 7ab254f5e4e6
Create Date: 2026-08-27 17:16:05.967244

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a961da61a0df'
down_revision: str | Sequence[str] | None = '7ab254f5e4e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('fighter_a_id', sa.UUID(), nullable=True),
    sa.Column('fighter_b_id', sa.UUID(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('weight_class', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('referee', sa.String(length=100), nullable=True),
    sa.Column('title_fight', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fighter_a_id'], ['fighters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fighter_b_id'], ['fighters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fights_event_id'), 'fights', ['event_id'], unique=False)
    op.create_index(op.f('ix_fights_fighter_a_id'), 'fights', ['fighter_a_id'], unique=False)
    op.create_index(op.f('ix_fights_fighter_b_id'), 'fights', ['fighter_b_id'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promotion', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.UUID(), nullable=True),
    sa.Column('ranking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_fighter_id'), 'rankings', ['fighter_id'], unique=False)
    op.drop_index(op.f('ix_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('events', sa.Column('venue', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('promotion', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('main_event', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('fighters', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('fighters', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('fighters', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('fighters', sa.Column('no_contests', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('ko_wins', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('submission_wins', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('decision_wins', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('fighters', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.drop_index(op.f('ix_semantic_cache_embedding_hnsw'), table_name='semantic_tool_cache', postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_semantic_cache_embedding_hnsw'), 'semantic_tool_cache', ['query_embedding'], unique=False, postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('fighters', 'source_url')
    op.drop_column('fighters', 'source')
    op.drop_column('fighters', 'decision_wins')
    op.drop_column('fighters', 'submission_wins')
    op.drop_column('fighters', 'ko_wins')
    op.drop_column('fighters', 'no_contests')
    op.drop_column('fighters', 'nationality')
    op.drop_column('fighters', 'last_name')
    op.drop_column('fighters', 'first_name')
    op.drop_column('events', 'source_url')
    op.drop_column('events', 'source')
    op.drop_column('events', 'main_event')
    op.drop_column('events', 'promotion')
    op.drop_column('events', 'status')
    op.drop_column('events', 'venue')
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_rankings_fighter_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_fights_fighter_b_id'), table_name='fights')
    op.drop_index(op.f('ix_fights_fighter_a_id'), table_name='fights')
    op.drop_index(op.f('ix_fights_event_id'), table_name='fights')
    op.drop_table('fights')
    # ### end Alembic commands ###
