"""add sharing to chat sessions

Revision ID: b947f28e0676
Revises: d835083479be
Create Date: 2026-08-27 19:44:49.979347

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b947f28e0676'
down_revision: str | Sequence[str] | None = 'd835083479be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_sessions', sa.Column('share_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_chat_sessions_share_id'), 'chat_sessions', ['share_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_share_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'share_id')
    op.drop_column('chat_sessions', 'is_public')
    # ### end Alembic commands ###
