"""add user_id to quiz session

Revision ID: c7f1c8ec704f
Revises: 6ed4a9912488
Create Date: 2026-08-24 13:23:49.725180

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f1c8ec704f"
down_revision: str | Sequence[str] | None = "6ed4a9912488"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz_sessions", sa.Column("user_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_quiz_sessions_user_id"), "quiz_sessions", ["user_id"], unique=False)
    op.create_foreign_key(None, "quiz_sessions", "user", ["user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quiz_sessions", type_="foreignkey")
    op.drop_index(op.f("ix_quiz_sessions_user_id"), table_name="quiz_sessions")
    op.drop_column("quiz_sessions", "user_id")
    # ### end Alembic commands ###
