"""Strict PROMPT compliance fields

Revision ID: d835083479be
Revises: 8694c2d3702c
Create Date: 2026-08-27 17:57:49.950725

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd835083479be'
down_revision: str | Sequence[str] | None = '8694c2d3702c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promotion', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('minimum_weight', sa.Float(), nullable=True),
    sa.Column('maximum_weight', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_fight_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('fight_id', sa.UUID(), nullable=False),
    sa.Column('card_type', sa.String(length=100), nullable=True),
    sa.Column('bout_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'fight_id', name='uix_event_fight')
    )
    op.create_index(op.f('ix_event_fight_cards_event_id'), 'event_fight_cards', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_fight_cards_fight_id'), 'event_fight_cards', ['fight_id'], unique=False)
    op.add_column('events', sa.Column('event_url', sa.String(length=1000), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('data_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('fighters', sa.Column('division', sa.String(length=100), nullable=True))
    op.add_column('fighters', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('fighters', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fighters', sa.Column('record', sa.String(length=100), nullable=True))
    op.add_column('fighters', sa.Column('current_ranking', sa.Integer(), nullable=True))
    op.add_column('fighters', sa.Column('active_status', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('fighters', sa.Column('profile_url', sa.String(length=1000), nullable=True))
    op.add_column('fighters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fighters', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fighters', sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fighters', sa.Column('data_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('fights', sa.Column('judge_scorecards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fights', sa.Column('bonus', sa.String(length=255), nullable=True))
    op.add_column('fights', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fights', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fights', sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fights', sa.Column('data_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('rankings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rankings', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rankings', sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rankings', sa.Column('data_version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rankings', 'data_version')
    op.drop_column('rankings', 'last_verified_at')
    op.drop_column('rankings', 'fetched_at')
    op.drop_column('rankings', 'created_at')
    op.drop_column('fights', 'data_version')
    op.drop_column('fights', 'last_verified_at')
    op.drop_column('fights', 'fetched_at')
    op.drop_column('fights', 'created_at')
    op.drop_column('fights', 'bonus')
    op.drop_column('fights', 'judge_scorecards')
    op.drop_column('fighters', 'data_version')
    op.drop_column('fighters', 'last_verified_at')
    op.drop_column('fighters', 'fetched_at')
    op.drop_column('fighters', 'created_at')
    op.drop_column('fighters', 'profile_url')
    op.drop_column('fighters', 'active_status')
    op.drop_column('fighters', 'current_ranking')
    op.drop_column('fighters', 'record')
    op.drop_column('fighters', 'date_of_birth')
    op.drop_column('fighters', 'country')
    op.drop_column('fighters', 'division')
    op.drop_column('events', 'data_version')
    op.drop_column('events', 'last_verified_at')
    op.drop_column('events', 'fetched_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'event_url')
    op.drop_index(op.f('ix_event_fight_cards_fight_id'), table_name='event_fight_cards')
    op.drop_index(op.f('ix_event_fight_cards_event_id'), table_name='event_fight_cards')
    op.drop_table('event_fight_cards')
    op.drop_table('weight_classes')
    # ### end Alembic commands ###
