"""Add advanced fighter stats

Revision ID: e91d03ee02d7
Revises: 1775e09fcf20
Create Date: 2026-08-23 18:18:21.156406

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e91d03ee02d7"
down_revision: str | Sequence[str] | None = "1775e09fcf20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fighters", sa.Column("title_defenses", sa.Integer(), nullable=True))
    op.add_column("fighters", sa.Column("championships", sa.JSON(), nullable=True))
    op.add_column("fighters", sa.Column("win_streak", sa.Integer(), nullable=True))
    op.add_column("fighters", sa.Column("team", sa.String(length=255), nullable=True))
    op.add_column("fighters", sa.Column("stance", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fighters", "stance")
    op.drop_column("fighters", "team")
    op.drop_column("fighters", "win_streak")
    op.drop_column("fighters", "championships")
    op.drop_column("fighters", "title_defenses")
    # ### end Alembic commands ###
