"""Initial migration

Revision ID: f2eff63f681a
Revises:
Create Date: 2026-08-22 20:15:06.554100

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector import sqlalchemy
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2eff63f681a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table("documents",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("title", sa.String(length=500), nullable=False),
    sa.Column("source", sa.String(length=1000), nullable=False),
    sa.Column("category", sa.String(length=100), nullable=False),
    sa.Column("source_type", sa.String(length=50), nullable=False),
    sa.Column("chunk_count", sa.Integer(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("source"),
    )
    op.create_index(op.f("ix_documents_category"), "documents", ["category"], unique=False)
    op.create_table("quiz_sessions",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("topic", sa.String(length=300), nullable=False),
    sa.Column("category", sa.String(length=100), nullable=True),
    sa.Column("difficulty", sa.String(length=50), nullable=False),
    sa.Column("num_questions", sa.Integer(), nullable=False),
    sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("chunks",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("document_id", sa.UUID(), nullable=False),
    sa.Column("content", sa.Text(), nullable=False),
    sa.Column("embedding", sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column("chunk_index", sa.Integer(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    op.create_table("quiz_results",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("session_id", sa.UUID(), nullable=False),
    sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("score", sa.Integer(), nullable=False),
    sa.Column("total_questions", sa.Integer(), nullable=False),
    sa.Column("score_percentage", sa.Float(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["session_id"], ["quiz_sessions.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_results_session_id"), "quiz_results", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_results_session_id"), table_name="quiz_results")
    op.drop_table("quiz_results")
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_table("quiz_sessions")
    op.drop_index(op.f("ix_documents_category"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
