import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, model_validator


class QuestionOption(BaseModel):
    """An option for a multiple choice question."""

    id: str = Field(description="Unique identifier for this option (e.g., 'A', 'B', 'C', 'D')")
    text: str = Field(description="The text of the option")


class Question(BaseModel):
    """A single multiple choice question generated by the LLM."""

    id: str = Field(description="Unique identifier for the question")
    text: str = Field(description="The question text")
    options: list[QuestionOption] = Field(description="The available options. Exactly 4 options required.")
    correct_option_id: str = Field(description="The ID of the correct option")
    explanation: str = Field(description="Explanation of why the correct option is correct")
    sources: list[str] | None = Field(default=None, description="Titles or IDs of source documents used")

    @model_validator(mode="after")
    def validate_options(self) -> "Question":
        if len(self.options) != 4:
            raise ValueError("Exactly 4 options are required per question.")
        valid_ids = {opt.id for opt in self.options}
        if self.correct_option_id not in valid_ids:
            raise ValueError(
                f"correct_option_id '{self.correct_option_id}' is not one of the option IDs: {valid_ids}",
            )
        return self


class QuizGeneratedData(BaseModel):
    """The complete structured output from the LLM when generating a quiz."""

    topic: str = Field(description="The general topic of this quiz")
    difficulty: str = Field(description="The difficulty level of the quiz")
    questions: list[Question] = Field(description="The list of generated questions")


class QuizGenerateRequest(BaseModel):
    """Request to generate a new quiz."""

    topic: str = Field(..., description="Topic of the quiz (e.g., 'Jon Jones career', 'UFC unified rules')")
    difficulty: str = Field(default="medium", description="Difficulty: 'easy', 'medium', 'hard'")
    num_questions: int = Field(default=5, ge=1, le=10, description="Number of questions to generate (1-10)")
    category: str | None = Field(default=None, description="Optional category filter for retrieval")
    fighter: str | None = Field(default=None, description="Optional fighter filter for retrieval")


class QuizSessionRead(BaseModel):
    """Read schema for a QuizSession (excludes the answer key)."""

    id: uuid.UUID
    topic: str
    difficulty: str
    num_questions: int
    questions: list[dict[str, Any]]
    created_at: datetime

    @model_validator(mode="before")
    @classmethod
    def strip_correct_answers(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "questions" in data and isinstance(data["questions"], list):
                sanitized_questions = []
                for q in data["questions"]:
                    safe_q = dict(q)
                    safe_q.pop("correct_option_id", None)
                    safe_q.pop("explanation", None)
                    sanitized_questions.append(safe_q)
                data["questions"] = sanitized_questions
        elif hasattr(data, "questions"):
            import copy
            sanitized_questions = []
            for q in data.questions:
                safe_q = copy.deepcopy(q)
                if isinstance(safe_q, dict):
                    safe_q.pop("correct_option_id", None)
                    safe_q.pop("explanation", None)
                sanitized_questions.append(safe_q)
            return {
                "id": data.id,
                "topic": data.topic,
                "difficulty": data.difficulty,
                "num_questions": data.num_questions,
                "questions": sanitized_questions,
                "created_at": data.created_at,
            }
        return data


class QuizSubmitRequest(BaseModel):
    """Request to submit answers for a quiz session."""

    session_id: uuid.UUID
    answers: dict[str, str] = Field(..., description="Mapping of question ID to the chosen option ID")


class QuestionResult(BaseModel):
    """Result for a single question."""

    question_id: str
    is_correct: bool
    selected_option_id: str | None
    correct_option_id: str
    explanation: str


class QuizSubmitResponse(BaseModel):
    """Response containing the graded quiz results."""

    session_id: uuid.UUID
    score: int
    total_questions: int
    score_percentage: float
    results: list[QuestionResult]
